class Autogenerated {
  User? user;

  Autogenerated({this.user});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    user = json['user: '] != null ? new User.fromJson(json['user: ']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user: '] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? firstName;
  String? lastName;
  String? phoneNumber;
  Null? confirmPassword;
  String? password;
  String? currentCountry;
  String? visitCountry;
  Null? residentCardId;
  String? balanceChargeCode;
  double? balance;
  Null? email;
  String? accountType;
  String? genderType;
  String? dateOfBirth;
  Null? avatarPhoto;
  Null? deviceId;
  bool? verification;

  User(
      {this.id,
      this.firstName,
      this.lastName,
      this.phoneNumber,
      this.confirmPassword,
      this.password,
      this.currentCountry,
      this.visitCountry,
      this.residentCardId,
      this.balanceChargeCode,
      this.balance,
      this.email,
      this.accountType,
      this.genderType,
      this.dateOfBirth,
      this.avatarPhoto,
      this.deviceId,
      this.verification});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    phoneNumber = json['phoneNumber'];
    confirmPassword = json['confirmPassword'];
    password = json['password'];
    currentCountry = json['currentCountry'];
    visitCountry = json['visitCountry'];
    residentCardId = json['residentCardId'];
    balanceChargeCode = json['balanceChargeCode'];
    balance = json['balance'];
    email = json['email'];
    accountType = json['accountType'];
    genderType = json['genderType'];
    dateOfBirth = json['dateOfBirth'];
    avatarPhoto = json['avatarPhoto'];
    deviceId = json['deviceId'];
    verification = json['verification'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['phoneNumber'] = this.phoneNumber;
    data['confirmPassword'] = this.confirmPassword;
    data['password'] = this.password;
    data['currentCountry'] = this.currentCountry;
    data['visitCountry'] = this.visitCountry;
    data['residentCardId'] = this.residentCardId;
    data['balanceChargeCode'] = this.balanceChargeCode;
    data['balance'] = this.balance;
    data['email'] = this.email;
    data['accountType'] = this.accountType;
    data['genderType'] = this.genderType;
    data['dateOfBirth'] = this.dateOfBirth;
    data['avatarPhoto'] = this.avatarPhoto;
    data['deviceId'] = this.deviceId;
    data['verification'] = this.verification;
    return data;
  }
}
