import 'dart:convert';
import 'package:api_test/models/nimadir.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import '../models/login_model.dart';

class Home_page extends StatefulWidget {
  const Home_page({Key? key});

  @override
  State<Home_page> createState() => _Home_pageState();
}

class _Home_pageState extends State<Home_page> {
  Autogenerated? nimadir;
  test_api() {
    login(login_model(
      password: "123456789",
      phoneNumber: "+998906936594",
      macAddress: "UPP2.230217.002",
    ));
  }

  Future<void> login(login_model model) async {
    try {
      final response = await http.post(
        Uri.parse(
            "http://ec2-54-199-249-118.ap-northeast-1.compute.amazonaws.com:7088/sos/api/auth/login"),
        headers: {'Content-Type': 'application/json'},
        body: json.encode(model.toJson()),
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        try {
          final body = response.body;

          if (body != null && body.isNotEmpty) {
            final json = jsonDecode(body);
            final result = json['object'];
            final data = Autogenerated.fromJson(result);
            setState(() {
              nimadir = data;
            });
          } else {
            print('API response body is null or empty');
          }
        } catch (e) {
          print(e);
        }
      } else {
        Navigator.pop(context);
        print('API request failed with status code: ${response.statusCode}');
      }
    } catch (e) {
      return;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: test_api,
      ),
      backgroundColor: Colors.white,
      appBar: AppBar(),
      body: Container(
        child: Text("${nimadir!.user!.id!}"),
      ),
    );
  }
}
